const ADD = 'ADD';
const DELETE = 'DELETE';
const SAVE_CARD = 'SAVE_CARD';
const DELETE_CARD = 'DELETE_CARD';
const SET_DATA_CARDS = 'SET_DATA_CARDS';
const SIGN_OUT_USER = 'SIGN_OUT_USER';
const AUTH_USER = 'AUTH_USER';
const STORAGE_DATA = 'STORAGE_DATA';
const TOGGLE_THEME = 'TOGGLE_THEME';

export const actions = {
  ADD,
  SAVE_CARD,
  DELETE,
  DELETE_CARD,
  SET_DATA_CARDS,
  SIGN_OUT_USER,
  AUTH_USER,
  STORAGE_DATA,
  TOGGLE_THEME,
};
