const ADD = 'ADD';
const DELETE = 'DELETE';
const SAVE_CARD = 'SAVE_CARD';
const DELETE_CARD = 'DELETE_CARD';
const SET_AUTH_USER_DATA = 'SET_AUTH_USER_DATA';
const SET_LOCAL_USER_DATA = 'SET_LOCAL_USER_DATA';
const SET_DATA_CARDS = 'SET_DATA_CARDS';

export const actions = {
  ADD,
  SAVE_CARD,
  DELETE,
  DELETE_CARD,
  SET_AUTH_USER_DATA,
  SET_LOCAL_USER_DATA,
  SET_DATA_CARDS,
};
